# Generated by Django 4.2.27 on 2026-02-16 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('cashout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payment_method', models.CharField(choices=[('mtn_mobile_money', 'MTN Mobile Money'), ('airtel_mobile_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer')], max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Full name of the mobile money or bank account holder', max_length=150, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('seller_note', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, help_text='Reference from external payment gateway (MTN/Airtel/Bank)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to='cashingapp.platform')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cashouts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_request', to='cashingapp.transaction')),
            ],
            options={
                'db_table': 'cashout_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
