# Generated by Django 4.2.27 on 2026-01-12 00:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0002_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('awaiting_clearance', 'Awaiting Clearance'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('disputed', 'Disputed')], default='initiated', max_length=30)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data from RP platform', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform_name', models.CharField(max_length=255)),
                ('domain', models.URLField(max_length=500)),
                ('return_url', models.URLField(help_text='URL to redirect after payment', max_length=500)),
                ('callback_url', models.URLField(help_text='URL for payment notifications', max_length=500)),
                ('mobile_money_api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_money_provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('other', 'Other')], default='mtn', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platforms',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('cashout', 'Cashout'), ('refund', 'Refund')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('mobile_money_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='cashingapp.wallet')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cashingapp.platform')),
                ('to_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='cashingapp.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platform',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentRequestItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('is_cleared', models.BooleanField(default=False, help_text='Buyer confirmed delivery')),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cashingapp.paymentrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_item', to='cashingapp.transaction')),
            ],
            options={
                'db_table': 'payment_request_items',
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='cashingapp.platform'),
        ),
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('mm_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('collection', 'Collection/Deposit'), ('disbursement', 'Disbursement/Cashout')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('external_reference', models.CharField(max_length=255, unique=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mm_transactions', to='cashingapp.platform')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_transaction', to='cashingapp.transaction')),
            ],
            options={
                'db_table': 'mobile_money_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('no_delivery', 'No Delivery'), ('wrong_item', 'Wrong Item'), ('damaged_item', 'Damaged Item'), ('incomplete_delivery', 'Incomplete Delivery'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('auto_refunded', 'Auto Refunded'), ('escalated', 'Escalated to Admin'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('payment_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='cashingapp.paymentrequestitem')),
                ('refund_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_refund', to='cashingapp.transaction')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('deposit', 'Deposit'), ('transfer', 'Transfer'), ('cashout', 'Cashout'), ('refund', 'Refund'), ('dispute_filed', 'Dispute Filed'), ('dispute_resolved', 'Dispute Resolved'), ('platform_registered', 'Platform Registered'), ('settings_updated', 'Settings Updated')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='cashingapp.platform')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
