# Generated by Django 4.2.27 on 2026-02-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0003_alter_dispute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='disputed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of the specific disputed item (not the full payment request item)', max_digits=12, null=True),
        ),
    ]
