# Generated by Django 4.2.27 on 2026-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0003_paymentrequest_platform_users_phone_number_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='domain',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
