# Generated by Django 4.2.27 on 2026-01-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0004_alter_platform_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='platform_domain',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
