# Generated by Django 4.2.27 on 2026-02-21 10:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0005_paymentrequestitem_deposited_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds earmarked for pending item deposits. These remain in the wallet (balance is unchanged) but cannot be freely spent until the reservation is completed or released.', max_digits=12),
        ),
    ]
