# Generated by Django 4.2.27 on 2026-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0005_users_platform_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN for transaction authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pin_attempts',
            field=models.IntegerField(default=0, help_text='Failed PIN attempts counter'),
        ),
        migrations.AddField(
            model_name='users',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, help_text='PIN locked until this timestamp', null=True),
        ),
    ]
