# Generated by Django 4.2.27 on 2026-03-02 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0006_wallet_reserved_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(db_index=True)),
                ('seller_email', models.EmailField(db_index=True, max_length=254)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('order_hash', models.CharField(max_length=128)),
                ('proof', models.JSONField(blank=True, null=True)),
                ('public_signals', models.JSONField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('tier_result', models.CharField(choices=[('green', 'Can pay all'), ('amber', 'Can pay some'), ('red', 'Cannot pay any'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('items_payable', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('binary_bracket', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_count', models.IntegerField(default=0)),
                ('include_cod', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['order_id', 'seller_email', '-generated_at'], name='bp_order_seller_idx')],
            },
        ),
    ]
