# Generated by Django 4.2.27 on 2026-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0008_users_zkp_commitment_hash_users_zkp_kyc_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceproof',
            name='order_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
