# Generated by Django 4.2.27 on 2026-03-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0010_alter_dispute_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequestitem',
            name='deposited_at',
        ),
        migrations.RemoveField(
            model_name='paymentrequestitem',
            name='is_deposited',
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='escrowed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount escrowed for this item', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='escrowed_at',
            field=models.DateTimeField(blank=True, help_text='When the escrow was made', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='is_escrowed',
            field=models.BooleanField(default=False, help_text='True when funds are transfered to sellers reserve balance, awaiting clearance'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('escrowed', 'Escrowed'), ('awaiting_clearance', 'Awaiting Clearance'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('disputed', 'Disputed')], default='initiated', max_length=30),
        ),
    ]
