# Generated by Django 4.2.27 on 2026-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0004_dispute_disputed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequestitem',
            name='deposited_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount deposited to buyer wallet for this item', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='deposited_at',
            field=models.DateTimeField(blank=True, help_text='When the deposit was made', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='is_deposited',
            field=models.BooleanField(default=False, help_text='True when buyer has deposited funds to their wallet for this item'),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='shopping_order_item_id',
            field=models.IntegerField(blank=True, help_text='Linked OrderItem.id on the shopping app — used for webhook status sync', null=True),
        ),
    ]
