# Generated by Django 4.2.27 on 2026-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0007_balanceproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='zkp_commitment_hash',
            field=models.CharField(blank=True, default='', help_text='Poseidon commitment hash from registration', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='zkp_kyc_root',
            field=models.CharField(blank=True, default='', help_text='Merkle root at time of verification', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='zkp_seller_id_hash',
            field=models.CharField(blank=True, default='', help_text='Seller ID hash from ZKP verification public signal', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='zkp_verified',
            field=models.BooleanField(default=False, help_text="Whether this seller's KYC proof has been verified via ZKP"),
        ),
        migrations.AddField(
            model_name='users',
            name='zkp_verified_at',
            field=models.DateTimeField(blank=True, help_text='When ZKP verification was completed', null=True),
        ),
    ]
