# Generated by Django 4.2.27 on 2026-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0009_alter_balanceproof_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('escalated', 'Escalated to Admin'), ('resolved_with_refund', 'Resolved With Refund'), ('resolved_without_refund', 'Resolved Without Refund')], default='submitted', max_length=50),
        ),
    ]
