# Generated by Django 4.2.27 on 2026-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0011_remove_paymentrequestitem_deposited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequestitem',
            name='deposited_at',
            field=models.DateTimeField(blank=True, help_text='When the escrow was made', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequestitem',
            name='is_deposited',
            field=models.BooleanField(default=False, help_text='True when funds are transfered to sellers reserve balance, awaiting clearance'),
        ),
    ]
