# Generated by Django 4.2.27 on 2026-04-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashingapp', '0012_paymentrequestitem_deposited_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('redirect_url', models.URLField(blank=True, max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('operation_type', models.CharField(choices=[('collection', 'Collection / Deposit'), ('disbursement', 'Disbursement / Cashout')], max_length=20)),
                ('pesapal_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('INVALID', 'Invalid'), ('REVERSED', 'Reversed'), ('UNKNOWN', 'Unknown')], default='PENDING', max_length=20)),
                ('confirmation_code', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('raw_submit_response', models.JSONField(blank=True, null=True)),
                ('raw_ipn_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pesapal_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
