"""
Django settings for faircashier project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from decouple import config

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "36e331bfd4f0.ngrok-free.app",
    "*.ngrok-free.app",
    "http://127.0.0.1:8000",  # E-commerce app
    "http://localhost:8000",   # E-commerce app
    "http://10.103.49.49:8000",  # E-commerce app
    "http://0.0.0.0:8000/",
    "edt-unfortunately-personality-singles.trycloudflare.com"
]


# Add Security Headers manually for better control
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

# Content Security Policy
CSP_FRAME_ANCESTORS = ["'self'", "http://localhost:8000", 'http://localhost:1337', 'https://administration-guards-behavior-pennsylvania.trycloudflare.com']  # E-commerce domain

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # E-commerce app
    "http://127.0.0.1:8000",
    'http://127.0.0.1:1337', 
    'http://localhost:1337',
    'https://edt-unfortunately-personality-singles.trycloudflare.com'
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 
                        'http://localhost:8000',
                        'http://127.0.0.1:8001', 
                        'http://localhost:8001',
                        'http://127.0.0.1:1337', 
                        'http://localhost:1337',
                        'https://edt-unfortunately-personality-singles.trycloudflare.com'
                        ]



# CSRF Configuration for Cross-Domain Access
CSRF_COOKIE_NAME = 'faircashier_csrftoken'  # Unique name
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_SAMESITE = 'Lax'  
CSRF_COOKIE_SECURE = False  # Set to True in production
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript access


# Allow iframe embedding
X_FRAME_OPTIONS = 'ALLOWALL'  # Or use ALLOW-FROM if you want to be specific

# Session Configuration for Cross-Domain Access
SESSION_COOKIE_NAME = 'faircashier_sessionid'  # Unique name to avoid conflicts
SESSION_COOKIE_DOMAIN = None  # Don't set domain for localhost
SESSION_COOKIE_HTTPONLY = True  # Keep for security
SESSION_SAVE_EVERY_REQUEST = True  # Ensure session is saved

SESSION_COOKIE_SAMESITE = 'Lax'  # Change from None to Lax
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# ZKP / Strapi (same Strapi instance as shopping app)
ZKP_STRAPI_URL       = os.getenv('ZKP_STRAPI_URL', 'http://localhost:1337')
ZKP_STRAPI_API_TOKEN = os.getenv('ZKP_STRAPI_API_TOKEN', '')

# Shopping app — used to pull seller KYC data for ZKP registration
SHOPPING_APP_URL             = os.getenv('SHOPPING_APP_URL', 'http://localhost:8000')
SHOPPING_APP_INTERNAL_SECRET = os.getenv('SHOPPING_APP_INTERNAL_SECRET', '')

#Pesapal API credentials
CONSUMER_KEY = os.getenv('CONSUMER_KEY')
CONSUMER_SECRET = os.getenv('CONSUMER_SECRET')

# ── PesaPal v3 integration ────────────────────────────────────────────────────
PESAPAL_ENVIRONMENT = os.getenv('PESAPAL_ENVIRONMENT', 'sandbox')
PESAPAL_USE_MOCK    = os.getenv('PESAPAL_USE_MOCK', 'False').lower() == 'true'
PESAPAL_IPN_URL     = os.getenv('PESAPAL_IPN_URL', '')
PESAPAL_CALLBACK_URL = os.getenv('PESAPAL_CALLBACK_URL', '')
PESAPAL_BRANCH      = os.getenv('PESAPAL_BRANCH', 'Fair Cashier')

# Cloudflare tunnel must be added to ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS
# when using a quick tunnel during development.  Extract the hostname from
# PESAPAL_IPN_URL automatically:
import urllib.parse as _urlparse
_tunnel_host = _urlparse.urlparse(PESAPAL_IPN_URL).hostname or ''
if _tunnel_host and _tunnel_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_tunnel_host)
if _tunnel_host:
    _tunnel_origin = f'https://{_tunnel_host}'
    if _tunnel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_tunnel_origin)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'guardian',
    'corsheaders',
    # Your apps...
    'cashingapp',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'faircashier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'faircashier.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Parse the DATABASE_URL environment variable
DATABASES = {
    'default': dj_database_url.config(default=config('DATABASE_URL'))
}

AUTH_USER_MODEL = 'cashingapp.Users'


LOGIN_URL = 'login_user'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'cashingapp.backends.EmailBackend',
    'guardian.backends.ObjectPermissionBackend',
]
# Use your custom user model for guardian
# Email of the anonymous user you created
ANONYMOUS_USER_NAME = "anonymous@example.com"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Password hashers (Argon2 first for PIN security)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # ← Strongest for PINs
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# ============= CACHE CONFIGURATION =============
# Cache configuration for duplicate transaction prevention
# Using in-memory cache for development (fast and simple)
# For production, consider Redis or Memcached

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'faircashier-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of cache entries
        }
    }
}



# ============================================================================
# LOGGING CONFIGURATION - For monitoring and debugging
# ============================================================================

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'transaction': {
            'format': '[{levelname}] {asctime} {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    
    'handlers': {
        # Console handler - prints to terminal
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        
        # General application log file
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'faircashier.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        
        # Transaction-specific log file
        'transaction_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'transactions.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'formatter': 'transaction',
        },
        
        # Duplicate detection log file
        'duplicate_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'duplicates.log'),
            'maxBytes': 5242880,  # 5MB
            'backupCount': 5,
            'formatter': 'transaction',
        },
        
        # Error-only log file
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errors.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    
    'loggers': {
        # Django framework loggers
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        # Your application loggers
        'cashingapp': {
            'handlers': ['console', 'file', 'transaction_file', 'duplicate_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        
        'cashingapp.views': {
            'handlers': ['console', 'transaction_file', 'duplicate_file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        
        'cashingapp.payment_processor': {
            'handlers': ['console', 'transaction_file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    
    # Root logger (catches everything not specified above)
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}
